### ISSUE TITLE
Loxberry Fehler mit  APT Vitoconnect

### ISSUE THREAD

**Issue by maestroat** [eloka080677/loxberry_vitoconnect#1]
FEHLER Vitoconnect: APT refresh: Die APT-Datenbank konnte nicht aktualisiert werden.

**Comment by eloka080677** [comment]
Habe es gerade nachgestellt. Die Fehlermeldung kommt nicht vom vitoconnect Plugin selbst. 

Im Rahmen des Updates der Dependencies z. B. Curl wird die apt Datenbank im Allgemeinen aktualisiert. Dabei gibt's mit einem repository ein Problem da dort die Signatur abgelaufen ist. Bei der Aktualisierung von rpimonitor knallt es dann. Und dies meckert er dann an

Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Err:4 https://dl.yarnpkg.com/debian stable InRelease
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging
Update rpimonitor Packages Status
Fetched 15.0 kB in 6s (2601 B/s)
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging
W: Some index files failed to download. They have been ignored, or old ones used instead.
14.06.2020 17:27:51 OK: Die APT-Datenbank wurde erfolgreich aktualisiert.
14.06.2020 17:27:54 INFO: Installiere zusätzliche Softwarepakete.
14.06.2020 17:27:54 INFO: Command: /usr/bin/dpkg --configure -a
Setting up rpimonitor (2.13-beta6) ...

Configuration file '/etc/rpimonitor/template/version.conf'
==> Modified (by you or by a script) since installation.
==> Package distributor has shipped an updated version.
What would you like to do about it ? Your options are:
Y or I : install the package maintainer's version
N or O : keep your currently-installed version
D : show the differences between the versions
Z : start a shell to examine the situation
The default action is to keep your current version.
*** version.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package rpimonitor (--configure):
end of file on stdin at conffile prompt
Errors were encountered while processing:
rpimonitor
